#!/usr/bin/env python3
"""
Process New - Pre-analyzed results push to Todoist
Generated by Claude Code (process_new skill) on 2026-04-22

Analysis source: Gmail MCP (30-day lookback, 50 threads) + Google Calendar
Run locally where Todoist API is accessible:
    pip install requests
    python3 _automation/push_to_todoist_2026_04_22.py
"""

import requests
import uuid
import sys

TODOIST_TOKEN = "bf17651eea9c2ce8ac6aa702172b5eef38bca8bf"
BASE_URL = "https://api.todoist.com/api/v1"

# ─────────────────────────────────────────────────────────────────────────────
# Pre-analyzed tasks from process_new skill run on 2026-04-22
# Threads analyzed: 50 | Calendar window: Apr 22–29, 2026
# ─────────────────────────────────────────────────────────────────────────────

TASKS = [
    # ── HIGH PRIORITY (red) ──────────────────────────────────────────────────
    {
        "content": "Attend Parent/Teacher Conference for Max - Google Meet 4 PM",
        "description": (
            "Ms. Prescott + Alexandra confirmed Thu Apr 23 at 4:00 PM EDT\n"
            "Google Meet link in calendar invite\n"
            "From: lkprescott@fcps.edu → confirmed by ahartnet@gmail.com"
        ),
        "priority": 4,
        "due_string": "2026-04-23",
        "labels": ["daily-plan", "calendar"]
    },
    {
        "content": "Verify tax return was filed — deadline was April 16",
        "description": (
            "TurboTax notified on Apr 17: 'The tax deadline was yesterday'\n"
            "Confirm return was filed or extension submitted to avoid penalties\n"
            "From: TurboTax@em1.turbotax.intuit.com"
        ),
        "priority": 4,
        "due_string": "today",
        "labels": ["daily-plan", "follow-up"]
    },
    {
        "content": "Review Guardian insurance claim — log in to Guardian Anytime",
        "description": (
            "Claim has been processed and is ready for review\n"
            "Log in to Guardian Anytime to see amounts paid by plan\n"
            "From: GuardianEOBAlerts@glic.com"
        ),
        "priority": 4,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    {
        "content": "Sign up for Dominion Energy Peak Time Rebates by April 30",
        "description": (
            "No obligation — decide if/how to save energy\n"
            "Deadline: April 30, 2026\n"
            "From: info@dominionenergyptr.com"
        ),
        "priority": 4,
        "due_string": "2026-04-30",
        "labels": ["daily-plan"]
    },
    # ── MEDIUM PRIORITY (orange) ─────────────────────────────────────────────
    {
        "content": "Review and act on GitHub: Claude app requesting updated permissions",
        "description": (
            "Claude GitHub App is requesting additional access to your account\n"
            "Review and approve or deny the permissions request\n"
            "From: noreply@github.com (Apr 21)"
        ),
        "priority": 3,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    {
        "content": "Vote in Fidelity: Trade Desk, Inc. Annual Meeting proxy",
        "description": (
            "Shareholder vote on important matters for THE TRADE DESK, INC.\n"
            "Log in to Fidelity to cast your vote — your vote counts\n"
            "From: Fidelity.Investments.email@shareholderdocs.fidelity.com (Apr 18)"
        ),
        "priority": 3,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    {
        "content": "Review Fidelity REI Systems Q1 2026 retirement plan statement",
        "description": (
            "Quarterly statement now available for REI SYSTEMS, INC retirement plan\n"
            "Log in to Fidelity to review\n"
            "From: Fidelity.Investments@mail.fidelity.com (Apr 17)"
        ),
        "priority": 3,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    {
        "content": "Review Bank of America monthly statement — Checking 3542",
        "description": (
            "Monthly statement is available for Anthony Checking 3542\n"
            "From: onlinebanking@ealerts.bankofamerica.com (Apr 18)"
        ),
        "priority": 3,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    {
        "content": "Review March HSA statement — Optum Financial account ending 346",
        "description": (
            "March HSA statement is ready to view\n"
            "Sign in to Optum Financial to review\n"
            "From: OptumFinancial@information.optum.com (Apr 17)"
        ),
        "priority": 3,
        "due_string": "today",
        "labels": ["daily-plan"]
    },
    # ── CALENDAR EVENTS ──────────────────────────────────────────────────────
    {
        "content": "Therapy appointment — Krista Hummer LPC, LMFT at 3:00 PM",
        "description": (
            "McLean Therapy, McLean VA\n"
            "(703) 822-1210 | www.mcleantherapy.com\n"
            "Google Meet link available in calendar invite"
        ),
        "priority": 3,
        "due_string": "2026-04-24",
        "labels": ["daily-plan", "calendar"]
    },
]

# ─────────────────────────────────────────────────────────────────────────────

def headers():
    return {
        "Authorization": f"Bearer {TODOIST_TOKEN}",
        "Content-Type": "application/json",
    }


def get_tasks():
    resp = requests.get(f"{BASE_URL}/tasks", headers=headers(), timeout=15)
    resp.raise_for_status()
    data = resp.json()
    return data.get("results", data) if isinstance(data, dict) else data


def delete_task(task_id):
    resp = requests.delete(f"{BASE_URL}/tasks/{task_id}", headers=headers(), timeout=15)
    return resp.status_code == 204


def create_task(task):
    resp = requests.post(
        f"{BASE_URL}/tasks",
        headers={**headers(), "X-Request-Id": str(uuid.uuid4())},
        json=task,
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


def main():
    print("=" * 70)
    print("PROCESS NEW — pushing pre-analyzed email tasks to Todoist")
    print("Analysis date : 2026-04-22")
    print("Threads scanned: 50 (30-day Gmail lookback)")
    print("Calendar window: Apr 22-29, 2026")
    print("=" * 70)

    # ── Step 1: delete stale daily-plan tasks ────────────────────────────────
    print("\n[1/2] Cleaning up old daily-plan tasks...")
    try:
        existing = get_tasks()
        removed = 0
        for t in existing:
            if "daily-plan" in t.get("labels", []):
                if delete_task(t["id"]):
                    removed += 1
                    print(f"      deleted: {t['content'][:65]}")
        print(f"      → removed {removed} old task(s)")
    except Exception as exc:
        print(f"      ⚠  Could not clean up: {exc}")

    # ── Step 2: create new tasks ─────────────────────────────────────────────
    print(f"\n[2/2] Creating {len(TASKS)} tasks...")
    icons = {4: "🔴", 3: "🟠", 2: "🔵", 1: "⚪"}
    created = 0
    for task in TASKS:
        try:
            create_task(task)
            created += 1
            icon = icons.get(task["priority"], "")
            due = task.get("due_string", "")
            print(f"      {icon} [{due}] {task['content'][:65]}")
        except requests.HTTPError as exc:
            print(f"      ❌ HTTP {exc.response.status_code}: {task['content'][:55]}")
        except Exception as exc:
            print(f"      ❌ Error: {exc} | {task['content'][:55]}")

    # ── Summary ──────────────────────────────────────────────────────────────
    print(f"\n{'=' * 70}")
    print(f"✅  Done — {created}/{len(TASKS)} tasks pushed to Todoist")
    print()
    print("  🔴 HIGH (DO NOW)")
    print("     • Parent/Teacher Conference for Max — Thu Apr 23 4 PM Google Meet")
    print("     • Verify tax return was filed (deadline was Apr 16)")
    print("     • Review Guardian insurance claim")
    print("     • Sign up for Dominion Energy Peak Time Rebates (by Apr 30)")
    print()
    print("  🟠 MEDIUM (DO SOON)")
    print("     • Review GitHub Claude app permissions request")
    print("     • Vote — Trade Desk Annual Meeting (Fidelity)")
    print("     • Review REI Systems Q1 retirement statement (Fidelity)")
    print("     • Review Bank of America monthly statement")
    print("     • Review March HSA statement (Optum)")
    print("     • Therapy appointment — Fri Apr 24 3 PM, McLean Therapy")
    print()
    if created < len(TASKS):
        print(f"  ⚠  {len(TASKS) - created} task(s) failed — check token / network and retry")
        sys.exit(1)


if __name__ == "__main__":
    main()
